### ISSUE TITLE
CSV id can not be recognized. ValueError: 'id' is not in list

### ISSUE THREAD

**Issue by eversatis** [tfrancoi/odoo_csv_import#20]
I am trying to  importing product data to odoo 12 with odoo_csv_import but constantly getting the following error. I do have the id column in the csv file. 
`odoo$ sudo odoo_import_thread.py -c connection.conf --file=product.template.csv --model=product.template    open product.template.csv
open product.template.csv
No External Id (id) column defined, please add one
Traceback (most recent call last):
  File "/usr/local/bin/odoo_import_thread.py", line 62, in <module>
    max_connection=max_connection, batch_size=batch_size, skip=int(args.skip), o2m=args.o2m)
  File "/usr/local/lib/python3.6/dist-packages/odoo_csv_tools/import_threaded.py", line 193, in import_data
    header, data = read_file(file_csv, delimiter=separator, encoding=encoding, skip=skip)
  File "/usr/local/lib/python3.6/dist-packages/odoo_csv_tools/import_threaded.py", line 143, in read_file
    check_id_column(header)
  File "/usr/local/lib/python3.6/dist-packages/odoo_csv_tools/import_threaded.py", line 131, in check_id_column
    raise ve
  File "/usr/local/lib/python3.6/dist-packages/odoo_csv_tools/import_threaded.py", line 128, in check_id_column
    header.index('id')
ValueError: 'id' is not in list
`

**Comment by tfrancoi** [comment]
The default separator is ";" probably that you have a different one in your file, you can specify the separator with --sep=

**Comment by eversatis** [comment]
> The default separator is ";" probably that you have a different one in your file, you can specify the separator with --sep=

Yes, I figured that out by exporting an example with this utility. But the --sep= parameter really helps in my case. This brilliant stuff saved my day! Thank you so much. You can mark the issue is resolved. Thank you again.
