### ISSUE TITLE
[bug] Issue with https

### ISSUE THREAD

**Issue by Navds** [tfrancoi/odoo_csv_import#21]
Does it have an issue with https? I always got the following error when trying simple export from the remote site using https. Yet, it works fine when I use my local odoo installation:
```
Traceback (most recent call last):
  File "/home/navds/.local/bin/odoo_export_thread.py", line 52, in <module>
    encoding=encoding)
  File "/home/navds/.local/lib/python3.6/site-packages/odoo_csv_tools/export_threaded.py", line 85, in export_data
    ids = object_registry.search(domain, context=context)
  File "/home/navds/.local/lib/python3.6/site-packages/odoolib/main.py", line 317, in proxy
    args, kw)
  File "/home/navds/.local/lib/python3.6/site-packages/odoolib/main.py", line 184, in proxy
    result = self.connector.send(self.service_name, method, *args)
  File "/home/navds/.local/lib/python3.6/site-packages/odoolib/main.py", line 140, in send
    return json_rpc(self.url, "call", {"service": service_name, "method": method, "args": args})
  File "/home/navds/.local/lib/python3.6/site-packages/odoolib/main.py", line 118, in json_rpc
    result = result_req.json()
  File "/home/navds/.local/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The command I use to export:

```
$ odoo_export_thread.py -c odoo.conf --model "product.template" --field "id,default_code,name" -s ";" --file export/product.template.csv
```

**Comment by tfrancoi** [comment]
It's working fine with https
what do you have in your conf file ? 
protocol should be jsonrpc**s** and port should be 443
